### PR TITLE
workflow(example): Fix example about update vlan

### LINKED ISSUE #11: can't update vlan info
I try to use pyaoscx (2.1.0) for update vlan information based on workflow.py script

i write the following script

```python
from pyaoscx.session import Session
from pyaoscx.pyaoscx_factory import PyaoscxFactory
from pyaoscx.vlan import Vlan
from pyaoscx.interface import Interface
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# There are two approaches to workflows, both using the session.
version = '10.04'
switch_ip = '10.200.11.225'
s = Session(switch_ip, version)
s.open('admin', 'MyPassword')

try:
    vlan100 = Vlan(s, 100)
    vlan100.get()
    print ("vlan100 {}".format(vlan100))

    #update vlan 100 (voice and description)
    vlan100.voice = True
    vlan100.name = "My Vlan"
    vlan100.description = "My description"
    print ("vlan100 {}".format(vlan100))
    vlan100.apply()

    vlan100.get()
    print ("vlan100 {}".format(vlan100))

    # ===========================================================
    # ===========================================================
    # ===========================================================

except Exception as error:
    print('Ran into exception: {}. Closing session.'.format(error))

finally:
    # At the end, the session MUST be closed
    s.close()
```

but don't work :

```
vlan100 Vlan, name: 'vlan100' ID: '100' and description: 'None'
vlan100 Vlan, name: 'My Vlan' ID: '100' and description: 'My description'
vlan100 Vlan, name: 'vlan100' ID: '100' and description: 'None'
```

### PR DESCRIPTION
**Pull request by alagoutte**
Missing selector='writable' when get vlan info

Fix #11

### CODE REVIEW

**Comment by alagoutte** [comment]
Hi,

Any news ?

**Comment by alagoutte** [comment]
Hi,

Some news ?

**Comment by tchiapuziowong** [comment]
Hi @alagoutte - can you please share the error you receive when executing?

**Comment by alagoutte** [comment]
@tchiapuziowong no error, only no description or voice parameter set...

**Pull request closed without merging**
